info:
  contact: {}
paths:
  /local/:
    get:
      description: Возвращает index.html
      produces:
      - text/html
      responses:
        "200":
          description: index.html
          schema:
            type: string
      summary: Отдать главную страницу локального приложения
      tags:
      - LocalManga
  /local/upload:
    post:
      consumes:
      - multipart/form-data
      description: Uploads an image file to the server
      parameters:
      - description: Image file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: File uploaded
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: No file received
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Upload an image
      tags:
      - LocalManga
swagger: "2.0"
